C:\Users\HariharaM12\PycharmProjects\L2\.venv\Scripts\python.exe C:\Users\HariharaM12\PycharmProjects\L2\laboratory\flc_extraction.py 
Traceback (most recent call last):
  File "C:\Users\HariharaM12\PycharmProjects\L2\laboratory\flc_extraction.py", line 1, in <module>
    from graph.value_extraction import invoke_value_extraction
  File "C:\Users\HariharaM12\PycharmProjects\L2\graph\value_extraction.py", line 28, in <module>
    faiss_index = FAISS.load_local("../faiss_index", embedding_model, allow_dangerous_deserialization=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HariharaM12\PycharmProjects\L2\.venv\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 1205, in load_local
    index = faiss.read_index(str(path / f"{index_name}.faiss"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HariharaM12\PycharmProjects\L2\.venv\Lib\site-packages\faiss\swigfaiss_avx2.py", line 11141, in read_index
    return _swigfaiss_avx2.read_index(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open ..\faiss_index\index.faiss for reading: No such file or directory

Process finished with exit code 1
